[package]
name = "discord_webhook"
version = "1.0.0"
edition = "2024"
description = "Rust library to send Discord webhooks."
license = "MIT"

[dependencies]
reqwest = { version = "0.11", features = ["blocking"]}
serde_json = "1.0.140"
serde = "1.0.219"